import Banner from "@/components/Banner";
import BestSellers from "@/components/BestSellers";
import Brands from "@/components/Brands";
import Products from "@/components/Products";
import Head from "next/head";

import Img from "../assets/07.png";

// import { Roboto } from "next/font/google";
import { Footer, Hero, Nav } from "../components";
import { GetStaticProps } from "next";
import { client } from "@/lib/sanity";

export default function Home({ hero, products }: any) {
  return (
    <>
      <Head>
        <title>Buy Apple Products -- Dawood</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Nav></Nav>
        <Hero hero={hero} />
        <Brands />
        <Products products={products} />
        <Banner />
        {/* <BestSellers /> */}

        {/* follow? */}
        {/* <section className="py-28 bg-m-gray">
          <h1 className="text-body text-center text-black ">
            Follow products and discounts on Instagram
          </h1>
          <div className="grid py-10  max-w-6xl mx-auto  grid-cols-6 gap-6">
            <img className="h-{200px]" src={Img.src} alt="" />
            <img className="h-{200px]" src={Img.src} alt="" />
            <img className="h-{200px]" src={Img.src} alt="" />
            <img className="h-{200px]" src={Img.src} alt="" />
            <img className="h-{200px]" src={Img.src} alt="" />
            <img className="h-{200px]" src={Img.src} alt="" />
          </div>
        </section> */}
        <Footer />
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const hero = await client.fetch(`*[_type == "banner"]`);
  console.log(hero);
  const products = await client.fetch(`*[_type == 'products']`);
  return {
    props: {
      hero,
      products,
    },
  };
};
